services:
    inspectable_stash_driver.inspector.memcached:
        class: Jadu\InspectableStashBundle\Inspector\MemcachedInspector
        # Memcached argument is set by MemcachedServiceCompilerPass from configuration
